include $(TOPDIR)commit.mk
include $(S)user.vmk
ifeq ( 999, $(USER_VERSION_BUILD) )
	USER_VERSION_NEXT_BUILD:=0
	USER_VERSION_NEXT_MINOR:=$(call domath,$(USER_VERSION_MINOR) + 1)
else
	USER_VERSION_NEXT_BUILD:=$(call domath,$(USER_VERSION_BUILD) + 1)
	USER_VERSION_NEXT_MINOR:=$(USER_VERSION_MINOR)
endif

ifeq ( 1000, $(USER_VERSION_NEXT_MINOR) )
	USER_VERSION_NEXT_MINOR=0
	USER_VERSION_NEXT_MAJOR=$(call domath,$(USER_VERSION_MAJOR) + 1)
else
	USER_VERSION_NEXT_MAJOR=$(USER_VERSION_MAJOR)
endif

USER_OUT:=$(B)codit$(TARGET_BIN_EXT)
user: TARGET_LARGE:=USER
user: TARGET_LIBS:=$(BIN_LIBS) $(Fl)shell32
user: TARGET_OBJECTS:=$(OBJECTS) $(O)user.o
user: paths $(OBJECTS) $(O)user.o
$(O)user.o: TARGET_LIBS:=$(OBJ_LIBS) $(Fl)shell32
$(O)user.o: $(PROCLST_H)