include $(TOPDIR)commit.mk
include $(TOPDIR)targets/test.vmk
ifeq ( 999, $(TEST_VERSION_BUILD) )
    TEST_VERSION_NEXT_BUILD:=0
    TEST_VERSION_NEXT_MINOR:=$(call domath,$(TEST_VERSION_MINOR) + 1)
else
    TEST_VERSION_NEXT_BUILD:=$(call domath,$(TEST_VERSION_BUILD) + 1)
    TEST_VERSION_NEXT_MINOR:=$(TEST_VERSION_MINOR)
endif

ifeq ( 1000, $(TEST_VERSION_NEXT_MINOR) )
    TEST_VERSION_NEXT_MINOR=0
    TEST_VERSION_NEXT_MAJOR=$(call domath,$(TEST_VERSION_MAJOR) + 1)
else
    TEST_VERSION_NEXT_MAJOR=$(TEST_VERSION_MAJOR)
endif

test: OUT=codit_test$(TAREXE)
test: TARGET_SMALL=test
test: TARGET_LARGE=TEST
test: OUTPUT=executable
