TEST_VERSION_FILE:=TEST_VERSION.mk
include $(TEST_VERSION_FILE)
ifeq ( 99999, $(TEST_VERSION_BUILD) )
    TEST_VERSION_NEXT_BUILD:=0
    TEST_VERSION_NEXT_MINOR:=$(call domath,$(TEST_VERSION_MINOR) + 1)
else
    TEST_VERSION_NEXT_BUILD:=$(call domath,$(TEST_VERSION_BUILD) + 1)
    TEST_VERSION_NEXT_MINOR:=$(TEST_VERSION_MINOR)
endif

ifeq ( 100, $(TEST_VERSION_NEXT_MINOR) )
    TEST_VERSION_NEXT_MINOR=0
    TEST_VERSION_NEXT_MAJOR=$(call domath,$(TEST_VERSION_MAJOR) + 1)
else
    TEST_VERSION_NEXT_MAJOR=$(TEST_VERSION_MAJOR)
endif

TEST_MAIN_FILE=CoditTest
test: MAIN_FILE=$(TEST_MAIN_FILE)
test: MAIN_C=$(MAIN_FILE).c
test: MAIN_O=$(O)$(MAIN_FILE).o
test: VERSION_PREPEND=TEST
test: VERSION_FILE=$(TEST_VERSION_FILE)
test: VERSION_BUILD=$(TEST_VERSION_BUILD)
test: VERSION_MINOR=$(TEST_VERSION_MINOR)
test: VERSION_MAJOR=$(TEST_VERSION_MAJOR)
test: VERSION_NEXT_BUILD=$(TEST_VERSION_NEXT_BUILD)
test: VERSION_NEXT_MINOR=$(TEST_VERSION_NEXT_MINOR)
test: VERSION_NEXT_MAJOR=$(TEST_VERSION_NEXT_MAJOR)
test: objects executable
	echo Begining Test Executable
	
$(O)$(TEST_MAIN_FILE).o: $(TEST_MAIN_FILE).c
	${CC} ${CFLAGS} ${Fc} "$<" ${Fo} "$@"