USER_VERSION_FILE:=USER_VERSION.mk
include $(USER_VERSION_FILE)
ifeq ( 99999, $(USER_VERSION_BUILD) )
    USER_VERSION_NEXT_BUILD:=0
    USER_VERSION_NEXT_MINOR:=$(call domath,$(USER_VERSION_MINOR) + 1)
else
    USER_VERSION_NEXT_BUILD:=$(call domath,$(USER_VERSION_BUILD) + 1)
    USER_VERSION_NEXT_MINOR:=$(USER_VERSION_MINOR)
endif

ifeq ( 100, $(USER_VERSION_NEXT_MINOR) )
    USER_VERSION_NEXT_MINOR=0
    USER_VERSION_NEXT_MAJOR=$(call domath,$(USER_VERSION_MAJOR) + 1)
else
    USER_VERSION_NEXT_MAJOR=$(USER_VERSION_MAJOR)
endif

USER_MAIN_FILE=codit
user: MAIN_FILE=$(USER_MAIN_FILE)
user: MAIN_C=$(USER_FILE).c
user: MAIN_O=$(O)$(USER_FILE).o
user: VERSION_PREPEND=USER
user: VERSION_FILE=$(USER_VERSION_FILE)
user: VERSION_BUILD=$(USER_VERSION_BUILD)
user: VERSION_MINOR=$(USER_VERSION_MINOR)
user: VERSION_MAJOR=$(USER_VERSION_MAJOR)
user: VERSION_NEXT_BUILD=$(USER_VERSION_NEXT_BUILD)
user: VERSION_NEXT_MINOR=$(USER_VERSION_NEXT_MINOR)
user: VERSION_NEXT_MAJOR=$(USER_VERSION_NEXT_MAJOR)
user: objects executable
	echo Building Main Executable
	
$(O)$(USER_MAIN_FILE).o: $(USER_MAIN_FILE).c
	${CC} ${CFLAGS} ${Fc} "$<" ${Fo} "$@"