include $(TOPDIR)commit.mk
include $(TOPDIR)targets/user.vmk
ifeq ( 999, $(USER_VERSION_BUILD) )
    USER_VERSION_NEXT_BUILD:=0
    USER_VERSION_NEXT_MINOR:=$(call domath,$(USER_VERSION_MINOR) + 1)
else
    USER_VERSION_NEXT_BUILD:=$(call domath,$(USER_VERSION_BUILD) + 1)
    USER_VERSION_NEXT_MINOR:=$(USER_VERSION_MINOR)
endif

ifeq ( 1000, $(USER_VERSION_NEXT_MINOR) )
    USER_VERSION_NEXT_MINOR=0
    USER_VERSION_NEXT_MAJOR=$(call domath,$(USER_VERSION_MAJOR) + 1)
else
    USER_VERSION_NEXT_MAJOR=$(USER_VERSION_MAJOR)
endif

user: OUT=codit$(TAREXE)
user: TARGET_SMALL=user
user: TARGET_LARGE=USER
user: OUTPUT=executable
